version: '3'

services:
  db:
    image: mysql/mysql-server:5.7
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=pass"
      - "MYSQL_USER=jordan"
      - "MYSQL_PASSWORD=pass"
      - "MYSQL_DATABASE=mybdd"
  superapachephp:
    build: ./
    ports:
      - "8010:80"
    links:
      - "db:db"
    working_dir: "./"
